### ISSUE TITLE
Validate `next` URL

### ISSUE THREAD

**Issue by ThiefMaster** [indico/flask-multipass#15]
http://flask.pocoo.org/snippets/62/

**Comment by arrdem** [comment]
We just dusted this code off today; for current Python 3.X builds it looks like

```
from urllib.parse import urlparse

def is_safe_url(target):
    ref_url = urlparse(request.host_url)
    test_url = urlparse(urljoin(request.host_url, target))
    return test_url.scheme in ("http", "https") and ref_url.netloc == test_url.netloc
```

Is this particular task still of interest? What would the preferred solution look like? A user-definable callback invoked during `set_next_url()`, or should this be "on by default" as part of `set_next_url()` perhaps as a hook method a user would have to subclass to disable?

**Comment by ThiefMaster** [comment]
this was done in #45
