### ISSUE TITLE
OpenID Connect support?

### ISSUE THREAD

**Issue by EdSchouten** [indico/flask-multipass#21]
Hi there,

We're planning on using Indico in combination with an OAuth2 server we've implemented on top of [Osin](https://github.com/RangelReale/osin). Today I noticed that this library does not yet implement OpenID Connect; it always calls into the UserInfo endpoint to obtain the user's identity, regardless of whether the OAuth2 service returns an ID Token. Our service didn't implement the UserInfo endpoint yet, so I just went ahead and added that. We'll likely need it for some other web applications as well.

Question: are you folks planning on adding OpenID Connect support to this library? This would effectively make the `endpoint`, `identifier_field` and `mapping` configuration options unnecessary for those providers.

**Comment by ThiefMaster** [comment]
No plans from our side yet, but if you were willing to contribute one we'd appreciate it!

Either as a part of the multipass core or as a standalone package (the latter is better if you plan to maintain it in the future) - in any case, feel free to pass by `#indico` on freenode if you have any questions related to developing such a provider.

**Comment by ThiefMaster** [comment]
Hey, support for OIDC recently landed in master (#26). I just published it as `0.3-dev` to PyPI if you are still interested and want to give it a try.
