### ISSUE TITLE
SQLAlchemy provider uses FlaskForm from Flask-WTF which is not a dependency

### ISSUE THREAD

**Issue by arrdem** [indico/flask-multipass#37]
A minor packaging issue I noticed while trying to clean up unused deps; `flask_multipass.providers.sqlalchemy` pulls `FlaskForm` from `flask_multipass._compat` which pulls it from `flask_wtf` which is not listed as a dependency of `Flask-Multipass`.

Choices for correction would appear to be listing `Flask-WTF` as a dependency of `Flask-Multipass[sqlalchemy]`, or reworking `flask_multipass._compat` to reference `wtforms.form.Form` instead.

**Comment by ThiefMaster** [comment]
You are right, Flask-WTF should be a dependency of the `sqlalchemy` and `ldap` extras.

**Comment by arrdem** [comment]
Cool, I can throw up a PR.
