### ISSUE TITLE
LDAP identity provider ignore the uid parameter

### ISSUE THREAD

**Issue by jouvin** [indico/flask-multipass#39]
The [Indico documentation](https://docs.getindico.io/en/latest/config/auth/#ldap) states that it is possible to define the attribute to use as the UID in the LDAP identity providder, using the `uid` parameter. Unfortunately this doesn't work because this parameter is not read by the provider but is set inconditionnaly to `uid` in the constructor of the LDAPProviderMixin class.

**Comment by ThiefMaster** [comment]
I think you misunderstood the code:

```python
self.ldap_settings.setdefault('uid', 'uid')
```

This sets it to `uid` if it's not present, otherwise it keeps the existing value.

**Comment by jouvin** [comment]
Strange... I didn't find the time to completely figure out how works the `ldap_setting` logic but the `uid` definition that I made in the LDAP identity provider was ignored until I added this line... Without it, it stayed defined to `samAccountName` (not sure who is defining it). So I have the feeling that the provider parameters are not loaded into `ldap_settings`...

**Comment by ThiefMaster** [comment]
Hm... maybe you didn't put it in the `ldap` dict but rather directly in the provider settings?

**Comment by jouvin** [comment]
Ah yes, I put it in the provider settings, I missed it had to be in the `ldap` dict, thus my problem! Sorry for the noise.
