### ISSUE TITLE
trying example, but can't find sqlalchemy provider

### ISSUE THREAD

**Issue by bdouxx** [indico/flask-multipass#48]
hi

playing with the example.
There is only 3 providers in http://0.0.0.0:10500/login/
```
Available login providers:
    GitHub
    Insecure dummy auth
    SSO
```
but where is the  provider "example_local" which is in the code?
```
from flask_multipass.providers.sqlalchemy import SQLAlchemyAuthProviderBase, SQLAlchemyIdentityProviderBase

multipass.register_provider(LocalAuthProvider, 'example_local')
multipass.register_provider(LocalIdentityProvider, 'example_local')
```

**Comment by ThiefMaster** [comment]
Not sure what you mean.. it's being defined right here: https://github.com/indico/flask-multipass/blob/master/example/example.py#L50-L61

the `example_local` is just the name used to register it.

**Comment by bdouxx** [comment]
hi,

there is 3 provider_map defined in example.cfg
https://github.com/indico/flask-multipass/blob/bd06489ca8d7862417516f63b81985f61e4bbec6/example/example.cfg.example#L88-L97
and I can connect to 'test_identity_provider' with   'Pig': 'pig123' with   url http://0.0.0.0:10500/login/test_auth_provider

but there is a local user too.
https://github.com/indico/flask-multipass/blob/bd06489ca8d7862417516f63b81985f61e4bbec6/example/example.py#L145-L146
It's possible to be connected with this user?

**Comment by bdouxx** [comment]
sorry
I do not master the language enough to solve this.

**Comment by ThiefMaster** [comment]
Umm do you actually know how this library is meant to be used? Because if you are not a python developer it's not particularly useful to you...

**Comment by bdouxx** [comment]
I'm not a developer, I'm a sysadmin, so I'm not an expert in python, and I only want to make a simple website with local account and ldap account. 
* step 1: use locals accounts with database to store users and use flask session: done
* step 2: use Flask-SQLAlchemy for access to the database: done
* step 3: use Flask-Login for manage session: done 
* step 4: use LDAP: Failed with flask-multipass to manage local and ldap.  Perhaps this module is not for me, I will try another module.

in the description it's write: 
> Flask-Multipass is an extension that provides a user authentication system for Flask which can use multiple backends (such as local users, LDAP and OAuth) simultaneously.

Perhaps I misunderstood the description, but I can't find example on the web for Flask-Multipass with local users.

**Comment by ThiefMaster** [comment]
OK, so flask-multipass would indeed be a good choice for you since it takes care of all the dirty ldap details. I'll have a look about the local providers in the example app..

**Comment by ThiefMaster** [comment]
I just had a look at my local example config; you just need this to use the local provider in the example app (with Test / 123):

```python
MULTIPASS_AUTH_PROVIDERS = {
    'local': {
        'type': 'example_local',
        'title': 'Local Accounts'
    },
}

MULTIPASS_IDENTITY_PROVIDERS = {
    'local': {
        'type': 'example_local',
    },
}

MULTIPASS_PROVIDER_MAP = {
    'local': 'local',
}
```

**Comment by bdouxx** [comment]
thanks a lot

It's OK with your help. My problem was with the field "type" ,  I didn't make the connection between the creation of  the provider "multipass.register_provider" and the cfg file.
