### ISSUE TITLE
SP not at server root

### ISSUE THREAD

**Issue by quist00** [indico/flask-multipass#63]
Hi, All.  First I would like to say thank you for all the work that went into this.  I am trying to get this working with [SAML](https://samltest.id/) as a first step before approaching my campus SSO managers, but I am hitting a dead end.  After some head scratching and some research, I think I have come to the conclusion that either flask-multipass or one of its dependencies assumes that the flask site will be at the root of the server rather than a subdirectory as it is in my case.  Eventually I get the following error message after logging in at the IDP- "Authentication failed: SAML login failed (The response was received at https://jb-serv.fullerton.edu/multipass/saml/saml/acs instead of https://jb-serv.fullerton.edu/escapeRoom/multipass/saml/saml/acs)".  It may be related to this validation check referenced here: https://github.com/onelogin/python3-saml/issues/83
As a consequence of all this, I have a few questions.

1. Is my assumption correct and without a feature enhancement, there would be no way for it to be configured to work for a site that is not served directly off the root?
2. If, my assumption is incorrect, what changes to the configuration do I need to make to eliminate the error I am seeing?
3. If someone has a working configuration that does SAML for a flask site not served from root, would they be willing to share it minus any sensitive data of course?

Thanks you for your time,

Dave

A couple of items that may help with helping me:

Here is my metadata link if that helps: https://jb-serv.fullerton.edu/escapeRoom/multipass/saml/saml/metadata

This is my saml config dictionary minus the certs for my SP.

```py
_my_saml_config = {
    # If enabled, errors are more verbose and received attributes are
    # printed to stdout
    'debug': True,
    'sp': {
        # this needs to match what you use when registering the SAML SP
        'entityId': 'https://jb-serv.fullerton.edu/escapeRoom',
        # these bindings usually do not need to be set manually; the URLs
        # are auto-generated
        # 'assertionConsumerService': {'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST'},
        # 'singleLogoutService': {'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'},
        # depending on your security config you may need to generate a
        # certificate and private key.
        # you can use https://www.samltool.com/self_signed_certs.php or
        # use `openssl` for it (which is more secure as it ensures the
        # key never leaves your machine)
        'x509cert': '''redacted''',
        'privateKey': '''redacted''',
        # persistent name ids are the default, but you can override it
        # with a custom format
        # 'NameIDFormat': 'urn:oasis:names:tc:SAML:2.0:nameid-format:persistent'
    },
    'idp': {
        # This metadata is provided by your SAML IdP. You can omit (or
        # leave empty) the whole 'idp' section in case you need SP
        # metadata to register your app and get the IdP metadata from
        # https://yourapp.example.com/multipass/saml/{auth-provider-name}/metadata
        # and then fill in the IdP metadata afterwards.
        'entityId': 'https://samltest.id/saml/idp',
        'x509cert': '''MIIDETCCAfmgAwIBAgIUZRpDhkNKl5eWtJqk0Bu1BgTTargwDQYJKoZIhvcNAQEL
BQAwFjEUMBIGA1UEAwwLc2FtbHRlc3QuaWQwHhcNMTgwODI0MjExNDEwWhcNMzgw
ODI0MjExNDEwWjAWMRQwEgYDVQQDDAtzYW1sdGVzdC5pZDCCASIwDQYJKoZIhvcN
AQEBBQADggEPADCCAQoCggEBAJrh9/PcDsiv3UeL8Iv9rf4WfLPxuOm9W6aCntEA
8l6c1LQ1Zyrz+Xa/40ZgP29ENf3oKKbPCzDcc6zooHMji2fBmgXp6Li3fQUzu7yd
+nIC2teejijVtrNLjn1WUTwmqjLtuzrKC/ePoZyIRjpoUxyEMJopAd4dJmAcCq/K
k2eYX9GYRlqvIjLFoGNgy2R4dWwAKwljyh6pdnPUgyO/WjRDrqUBRFrLQJorR2kD
c4seZUbmpZZfp4MjmWMDgyGM1ZnR0XvNLtYeWAyt0KkSvFoOMjZUeVK/4xR74F8e
8ToPqLmZEg9ZUx+4z2KjVK00LpdRkH9Uxhh03RQ0FabHW6UCAwEAAaNXMFUwHQYD
VR0OBBYEFJDbe6uSmYQScxpVJhmt7PsCG4IeMDQGA1UdEQQtMCuCC3NhbWx0ZXN0
LmlkhhxodHRwczovL3NhbWx0ZXN0LmlkL3NhbWwvaWRwMA0GCSqGSIb3DQEBCwUA
A4IBAQBNcF3zkw/g51q26uxgyuy4gQwnSr01Mhvix3Dj/Gak4tc4XwvxUdLQq+jC
cxr2Pie96klWhY/v/JiHDU2FJo9/VWxmc/YOk83whvNd7mWaNMUsX3xGv6AlZtCO
L3JhCpHjiN+kBcMgS5jrtGgV1Lz3/1zpGxykdvS0B4sPnFOcaCwHe2B9SOCWbDAN
JXpTjz1DmJO4ImyWPJpN1xsYKtm67Pefxmn0ax0uE2uuzq25h0xbTkqIQgJzyoE/
DPkBFK1vDkMfAW11dQ0BXatEnW7Gtkc0lh2/PIbHWj4AzxYMyBf5Gy6HSVOftwjC
voQR2qr2xJBixsg+MIORKtmKHLfU''',
        'singleSignOnService': {
            'url': 'https://samltest.id/idp/profile/SAML2/Redirect/SSO',
            'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        },
        # If you do not want to perform a SAML logout when logging out
        # from your application, you can omit this section
        'singleLogoutService': {
            'url': 'https://samltest.id/idp/profile/SAML2/Redirect/SLO',
            'binding': 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
        }
    },
    # These advanced settings allow you to tune the SAML security options.
    # Please see the documentation on https://github.com/onelogin/python3-saml
    # for details on how they behave. Note that by requiring signatures,
    # you usually need to set a cert and key on your SP config, but for
    # testing you may want to disable all signing-related options.
    'security': {
        'nameIdEncrypted': False,
        'authnRequestsSigned': False,
        'logoutRequestSigned': False,
        'logoutResponseSigned': False,
        'signMetadata': False,
        'wantMessagesSigned': False,
        'wantAssertionsSigned': False,
        'wantNameId' : True,
        'wantNameIdEncrypted': False,
        'wantAssertionsEncrypted': False,
        'allowSingleLabelDomains': False,
        'signatureAlgorithm': 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',
        'digestAlgorithm': 'http://www.w3.org/2001/04/xmlenc#sha256'
    },
    # You can set contact information which will be included in the SP
    # metadata; it is up to the IdP if/how this information is used:
    # 'contactPerson': {
    #     'technical': {
    #         'givenName': 'technical_name',
    #         'emailAddress': 'technical@example.com'
    #     },
    #     'support': {
    #         'givenName': 'support_name',
    #         'emailAddress': 'support@example.com'
    #     }
    # },
    # 'organization': {
    #     'en-US': {
    #         'name': 'sp_test',
    #         'displayname': 'SP test',
    #         'url': 'http://sp.example.com'
    #     }
    # }
}
```

**Comment by ThiefMaster** [comment]
That sounds more like a configuration issue with  your Flask app - it doesn't seem to be aware that it's running in a subpath.

Flask-Multipass is using the normal `url_for()` logic of Flask, which seems to not include your subpath.

**Comment by quist00** [comment]
Hi, Adrian

I wanted to thank you for taking the time to get back to me with your suggestion.  I guess I don't understand why url_for() would have no issue getting back the subpath when it creates my navigation for things like the login page {{ url_for('login') }})  successfully (https://jb-serv.fullerton.edu/escapeRoom/login/) but it gets dropped  from path where the IDP tries to communicate back.

Nevertheless, I tried setting the APPLICATION_ROOT using several methods and locations, but doing so did not appear to have any impact that I could notice. No even breaking anything.  My attempts were not helped by the apparent design of the local flask server to ignore that setting, so I guess I am going to have to work through the process of figuring out how to remotely debug and see where that gets me.  I will give that a whirl and report back.  Thanks again.

**Comment by quist00** [comment]
Remote debugging was quite the adventure.  It seemed to lead me to these two lines of code below as the root of my issue.  For whatever reason current_app does not include the subpath, so it combines the server address with self.saml_acs_uri to make the response destination.  All my attempts to set an application root or script name whether before or after the app is instantiated seem to have no impact on this, so if someone can confirm it works for a subdirectory and could document the process, I think that would be a great addition long term.  In the short term, I plan to try to make it work running from the root of a subdomain since that seems to have more traction for my current skill set, so I will close this out as an issue at this time.

`        self.saml_acs_uri = self.settings.setdefault('saml_acs_uri', f'/multipass/saml/{self.name}/acs')
  ...
        current_app.add_url_rule(self.saml_acs_uri, self.saml_acs_endpoint, self._saml_acs, methods=('GET', 'POST'))
  `
