### ISSUE TITLE
Type error on init_app

### ISSUE THREAD

**Issue by nchietala** [indico/flask-multipass#71]
```
File ".../site-packages/flask_multipass/util.py", line 146, in resolve_provider_type
entry_points = importlib_entry_points(group=base._entry_point, name=type_)

TypeError: entry_points() for an unexpected keyword argument 'group'
```

I see this error and version 0.5 dies while loading.
It's trying to call `importlib.metadata.entrypoints` but that doesn't have a group argument.

**Comment by ThiefMaster** [comment]
On which Python version does that happen?

**Comment by nchietala** [comment]
3.10.3

**Comment by nchietala** [comment]
Correction: 3.9.5, the problem doesn't seem to occur on the 3.10 environment.

**Comment by ThiefMaster** [comment]
OK that makes more sense, because there were some significant changes to `importlib.metadata` between 3.9 and 3.10.

**Comment by nchietala** [comment]
I'm thinking something like
```py
if sys.version_info < (3, 10):
    entry_points= [ep for ep in entry_points().get(base._entry_point, []) if ep.name == type_]
else:
    entry_points= entry_points(group=base._entry_point, name=type_)
```

**Comment by ThiefMaster** [comment]
first of all i need to get the tests to fail ;) maybe i'm mocking too much there...

**Comment by ThiefMaster** [comment]
ok, found a minimal repro that makes use of the real entrypoints instead of mocked ones

```py
def test_load_providers():
    app = Flask('test')
    app.config['SECRET_KEY'] = 'testing'
    app.config['MULTIPASS_AUTH_PROVIDERS'] = {'test': {'type': 'static'}}
    app.config['MULTIPASS_IDENTITY_PROVIDERS'] = {'test': {'type': 'static'}}
    app.config['MULTIPASS_PROVIDER_MAP'] = {'test': 'test'}
    Multipass(app)
```

**Comment by nchietala** [comment]
That seems to be behaving now, thank you.

**Comment by ThiefMaster** [comment]
v0.5.1 is now released

**Comment by ThiefMaster** [comment]
While updating another extension I realized that it's probably much better/easier/cleaner to simply add `importlib-metadata` as a dependency and using that instead of the stdlib version. No need for version-specific code that way.

I might change this in a point release in order to be less exposed to future changes in `importlib.metadata`.
